server:
  port: 9090
spring:
  application.name: Syte.ai
  h2:
    console.enabled: true
  datasource:
    url: jdbc:h2:file:./mydb
    driverClassName: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: update

grpc:
  server:
    port: 9091